# -*- coding: utf-8 -*-
"""6101_Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SFxIojseXRROGUP8wafJEKHO0n8d9Zfp
"""

import math
import pandas as pd

a,b,c,Zsn,Zse= 11.309,4.119,4.300,50,34 

DataFrame={"H":[],"K":[],"L":[],"S_G(Complex Quantity)":[],"Intensity (S_G×S_G*)":[]}
df=pd.DataFrame(data=DataFrame)

Sn=[[0.1168927311363464,  0.2500000000000000,  0.0908027872013270],
    [0.8831072688636540,  0.7500000000000000,  0.9091972127986732], 
    [0.3831072688636535,  0.7500000000000000,  0.5908027872013268],
    [0.6168927311363460,  0.2500000000000000,  0.4091972127986732]]

Se=[[0.8579862927601806,  0.2500000000000000,  0.4752652369705491],
    [0.1420137072398193,  0.7500000000000000,  0.5247347630294510],
    [0.6420137072398194,  0.7500000000000000,  0.9752652369705490],
    [0.3579862927601807,  0.2500000000000000,  0.0247347630294509]]

indices = [[h,k,l] for h in range(0,7) for k in range(0,3) for l in range(0,3)]
for [h,k,l] in indices:
  if h+k+l==0:
    continue
  else:
    X = [0] *2
    for elem in Sn:
      theta=2*math.pi*(h*elem[0]+k*elem[1]+l*elem[2])
      X[0]=X[0]+Zsn*math.cos(theta)
      X[1]=X[1]+Zsn*math.sin(theta)
    for elem in Se:
      theta=2*math.pi*(h*elem[0]+k*elem[1]+l*elem[2])
      X[0]=X[0]+Zse*math.cos(theta)
      X[0]=X[0]+Zse*math.sin(theta)
  intensity=X[0]*X[0]+X[1]*X[1]
  arr=[h,k,l,str(X[0])+" + "+str(X[1])+"i",intensity]
  n=len(df)
  df.loc[n]=arr            
display(df)